### PR TITLE
added scroll

### PR DESCRIPTION
**Pull request by Rajat-patel19**
i have added scroll to the button

### CODE REVIEW

**Comment by Serjeel-Ranjan-911** [comment]
very good work. let's merge your changes. also let's exchange a follow. have great time on GitHub @Rajat-patel19

**Comment by Rajat-patel19** [comment]
For sure brother, Can you please help me out in open source community

**Comment by Serjeel-Ranjan-911** [comment]
yeah sure we are here to help each other

**Comment by Rajat-patel19** [comment]
Brother can you share your linkedin or twitter handle

**Comment by Serjeel-Ranjan-911** [comment]
https://serjeel-ranjan.netlify.com/
my portfolio here. you can find link here @Rajat-patel19

**Pull request merged**
